#!/bin/bash

set -e

apt-get install -y libaio1 libpcsclite1

wget -O /root/vmware.bundle http://cutiefly.cubbington.eu.widgit.com/vmware-workstation-linux-latest
chmod u+x /root/vmware.bundle
/root/vmware.bundle

if [ ! -f /etc/vmware/netmap.conf ] ; then
cat << EOF > /etc/vmware/netmap.conf
# This file is automatically generated.
# Hand-editing this file is not recommended.
network0.name = "Bridged"
network0.device = "vmnet0"
network1.name = "HostOnly"
network1.device = "vmnet1"
network8.name = "NAT"
network8.device = "vmnet8"
EOF
fi

apt-get install -y linux-headers-$(uname -r)
cd /usr/lib/vmware/modules/source
git clone https://github.com/mkubecek/vmware-host-modules
cd vmware-host-modules
# this will need changing if the output of "vmware --version" changes significantly
git checkout workstation-$(vmware --version | sed -e's/VMware Workstation //' | cut -d' ' -f1)
make install

cat << EOF > /etc/modules-load.d/vmware-modules.conf
vmmon
vmnet
EOF
