#!/bin/bash

set -e

# Old method
#ldd /usr/lib/vmware/bin/vmware-vmx
#/usr/lib/vmware/bin/vmware-vmx --new-sn NJ204-6110J-08KDQ-0VAKP-9TVJJ
#systemctl enable vmware.target

apt-get install -y libaio1 libpcsclite1

wget -O /root/vmware.bundle http://cutiefly.cubbington.eu.widgit.com/vmware-workstation-linux-latest
chmod u+x /root/vmware.bundle
/root/vmware.bundle

if [ ! -f /etc/vmware/netmap.conf ] ; then
cat << EOF > /etc/vmware/netmap.conf
# This file is automatically generated.
# Hand-editing this file is not recommended.
network0.name = "Bridged"
network0.device = "vmnet0"
network1.name = "HostOnly"
network1.device = "vmnet1"
network8.name = "NAT"
network8.device = "vmnet8"
EOF
fi

# New method
/usr/bin/vmware --version || true
/usr/lib/vmware/bin/licenseTool enter "0562M-0GJ8Q-08CJA-0230P-3ELPJ" "" "" "16.0+" "VMware Workstation" /usr/lib/vmware || true
