#!/bin/bash

set -e
set -x

if [ "$PACKER_BUILDER_TYPE" != "vmware-iso" ]; then
  exit 0
fi

echo Installing VMware prerequisites
apt install -y libaio1 libpcsclite1

echo Fetching VMware workstation
wget -O ~/vmware.bin.sh https://www.vmware.com/go/getworkstation-linux

echo Installing VMware workstation
sh ~/vmware.bin.sh --console --required --eulas-agreed

echo Performing post-installation appeasement of packer and vagrant plugin

# required to keep the vagrant plugin happy :rolleyes:
cat <<EOF > /etc/init.d/vmware
#!/bin/bash

/usr/bin/vmware-networks --status
EOF
chmod +x /etc/init.d/vmware

# hacks to make packer work!
mkdir -p /etc/vmware/vmnet8/dhcpd
cd /etc/vmware/vmnet8
ln -s dhcpd dhcp
ln -s dhcpd.conf dhcp/dhcp.conf

mkdir -p /etc/vmware/vmnet1/dhcpd
cd /etc/vmware/vmnet1
ln -s dhcpd dhcp
ln -s dhcpd.conf dhcp/dhcp.conf

cat <<EOF > /etc/vmware/netmap.conf
# This file is automatically generated.
# Hand-editing this file is not recommended.
network0.name = "Bridged"
network0.device = "vmnet0"
network1.name = "HostOnly"
network1.device = "vmnet1"
network2.name = "NAT"
network2.device = "vmnet8"
EOF

# disabled due to issues when bootstrapping new boxes under vmware.
# enable when ready
# systemctl enable vmware.target

apt install -y open-vm-tools
mkdir -p /mnt/hgfs